#! python3

import re, pyperclip

# Create a regex for phone numbers
phoneRegex = re.compile(r'''
# 415.555.000, 415-555-000, 555-000, (415) 555-0000, 555-0000 ext 12345, ext. 12345, x12345

((\d\d\d)|(\(\d\d\d)))?     # area code (optional)
(\s|-)                      # first separator
\d\d\d                      # first 3 digits
-                           # separator
\d\d\d\d                    # last 4 digits
(((ext(\.)?\s)|x)           # extension word-part (optional)
(\d{2,5}))?                 # extension number-part (optional)
''', re.VERBOSE)

#Create a regex for email addresses
emailRegex = re.compile(r'''
# some.+_thing@(\d{2,5}))?.com

[a-zA-Z0-9_.+]+     # name part
@                   # @ symbol
[a-zA-Z0-9_.+]+     # domain name part

''', re.VERBOSE)

#Get the text off the clipboard
text = pyperclip.paste()

#Extract the email/phone from this text
extractedPhone = phoneRegex.findall(text)
extractedEmail = emailRegex.findall(text)

print(extractedPhone)
print(extractedEmail)

#TODO:  Copy the extracted email/phone to the clipboard


================================= RESTART: C:\Users\Ryan\MyPythonScripts\phoneAndEmail.py =================================
Traceback (most recent call last):
  File "C:\Users\Ryan\MyPythonScripts\phoneAndEmail.py", line 16, in <module>
    ''', re.VERBOSE)
  File "C:\Users\Ryan\AppData\Local\Programs\Python\Python37\lib\re.py", line 234, in compile
    return _compile(pattern, flags)
  File "C:\Users\Ryan\AppData\Local\Programs\Python\Python37\lib\re.py", line 286, in _compile
    p = sre_compile.compile(pattern, flags)
  File "C:\Users\Ryan\AppData\Local\Programs\Python\Python37\lib\sre_compile.py", line 764, in compile
    p = sre_parse.parse(p, flags)
  File "C:\Users\Ryan\AppData\Local\Programs\Python\Python37\lib\sre_parse.py", line 944, in parse
    raise source.error("unbalanced parenthesis")
re.error: unbalanced parenthesis at position 118 (line 4, column 25)
